version: '3.8'
services:  
  backend:    
    build:      
      context: ./backend    
    ports:      
      - "5000:5000"    
    volumes:      
      - ./backend:/app    
    environment:      
      - FLASK_ENV=development  

  website:    
    build:      
      context: ./website    
    ports:      
      - "3000:3000"    
    volumes:      
      - ./website:/app